### ISSUE TITLE
Cart 설계

### ISSUE THREAD

**Issue by commety** [GDSC-PKNU-Official/24_2_BE_Beginner_Week2_UNOFFICIAL#7]
## ✅ Cart 역할
List<Product>로 직접 넣는 것보다 Client가 Product의 id와 수량만 넘겨주면 
거기에 맞는 Product를 찾아 Cart의 적절한 자료구조에 넣는 것이 좋아보입니다.
Cart는 사용자로부터 유효한 Product를 담고, 
사용자가 주문하면 주문에 필요한 정보를 Order에게 넘깁니다.
## ✏️ Cart 구현 목표
Cart는 사용자(Client)로부터 id, 수량(stock)을 받습니다. 
id가 유효한지, stock이 유효한지 체크합니다.
유효하다면 유효한 정보를 담는 적절한 자료구조에 담습니다.
자료구조는 고민중입니다.
이때 사용자는 주문을 할지 취소를 할지 결정하며
주문을 하면 Order에게 자료구조를 넘깁니다. 
아마 조합방식을 사용해 Order (makeOrder 메서드에 넘깁니다)
취소를 하면 해당 자료구조를 비웁니다.
## 📄 자료구조 설정
HashMap (json 형식)으로 고민중에 있습니다.

**Comment by xxubin04** [comment]
원래는 HashMap 써서 (가격, 수량) 받으려고 했었습니다! 근데 장바구니에서 항목을 빼는 기능도 넣다보니 이름도 있어야 할 것 같아서 ArrayList로 2차원 배열로 구현해두었습니다. 어떤 자료구조로 하는게 좋을까요?

**Comment by commety** [comment]
매개변수로 product의 id(long), product의 수량(quantity, int)를 받고 거기에 맞는 product를 cart의 적절한 자료구조에 담을 건데 담는 것을 취소하면 cart 자신의 유효한 product를 지우면 되니 2차원 Array까지는 안 써도 될 거 같습니다. 
주문에 필요한 정보는 상품 id, 상품명, 상품 가격, 상품 수량입니다.
그리고 아마 Cart 클래스는 Order 클래스를 조합해야 될 거 같습니다.
정보 전달을 위한 DTO를 만드셔도 되고 아니면 HashMap으로 
``` json
{
"id": productId,
"name": productName,
"quantity":  productQuantity,
"price": productPrice,
}
```
위와 같은 형식으로 넘겨주는 것도 괜찮아 보입니다.
구현하신거 issue나 커밋하셔서 보여주시면 코드리뷰로 의견드리겠습니다!

**Comment by xxubin04** [comment]
넵 감사합니다! 그러면 구현해보고 커밋하도록 하겠습니당

**Comment by squareCaaat** [comment]
#10에서 Cart 구현 목표참고해주세요~
