### ISSUE TITLE
Cart, Customer 설계, Main 동작방식 

### ISSUE THREAD

**Issue by xxubin04** [GDSC-PKNU-Official/24_2_BE_Beginner_Week2_UNOFFICIAL#8]
### 1. 상품 등록 

Customer가 장바구니에 담고자 하는 상품의 이름(productId)과 상품 개수(stock)을 입력하면, 

- 장바구니의 한도 개수인 50개를 넘지 않는다면, 상품 추가
   - 이미 장바구니에 있는 상품이라면, stock만 증가
   - 장바구니에 없는 상품이라면, 상품의 이름과 개수 등록
- 장바구니의 한도 개수인 50개를 넘는다면, 예외

<br>

### 2. 상품 삭제 

Customer가 장바구니에서 삭제하고자 하는 상품의 이름(productId)과 상품 개수(stock)를 입력하면,

- 삭제하고자 하는 상품이 장바구니(cart)에 있다면
  - 삭제하고자 하는 상품의 개수가 장바구니에 존재하는 개수보다 많다면, 개수를 0으로 만들기
  - 삭제하고자 하는 상품의 개수가 장바구니에 존재하는 개수보다 적다면, 삭제하고자 하는 개수만큼 원래의 개수에서 빼기
- 삭제하고자 하는 상품이 장바구니에 없다면,
  - 해당 상품을 찾을 수 없음을 알리기

<br>

### 3. 카트에 담긴 상품들의 총액 계산

CartDTO를 통해 productId로 해당 상품의 가격과 개수를 찾아 계산해서 반환 

<br>
<br>

## Customer 흐름

- 등록된 주소 수정
- 등록된 전화번호 수정
- 잔액 알려주는 기능
- 잔액 인출
- 잔액 입금

<br>
<br>

## Main 동작방식

단어를 입력받아서 해당 기능을 수행하는 걸로 할까요?

`modifyAdd` - modifyAddress() - 주소 변경
`modifyPhone` - modifyPhoneNumber() - 전화번호 변경
`account` - accountCheck() - 잔액 확인 
`withdraw` - withdrawAccount() - 잔액 인출
`deposit` - depositAccount() - 잔액 입금

`add` - addProduct() - 장바구니에 상품 추가
`delete` - deleteProduct() - 장바구니에서 상품 제거
`total` - getTotal() - 장바구니에 담긴 상품 총액 출력 

<br>

**Comment by commety** [comment]
## ⚙️ main 에서 동작
- 고객이 상품을 조회하기
  - ProductDao 클래스가 파일로부터 데이터를 읽어서 상품 목록을 만듭니다.
  - main 메서드에서 사용자가 `list` 입력 시 상품 목록을 출력합니다.
- 고객이 상품을 장바구니에 담기
  - main 메서드에서 사용자가 `add` 입력 후 상품 id 와 상품 수량을 입력 받아
  장바구니에 추가합니다.
    - 유효성 검사는 `add` 명령 때 수행됩니다.
    - 이때 Cart 클래스는 상품의 총액도 계산합니다.
- 고객이 장바구니에 담은 상품을 주문하기
  - 사용자가 `order` 입력 시 장바구니에 담긴 물품의 정보를 담은 OrderSheet를 
  Customer 클래스에 List<OrderSheet> 형태로 저장합니다.
- 고객이 자신이 주문서를 확인하기
  - 사용자가 `show order` 입력 시 Customer 클래스가 가지고 있는 모든 OrderSheet를 출력합니다.

이상 간단한 흐름을 짜봤습니다.

**Comment by commety** [comment]
상품 재고(stock)와 고객이 주문할 수량(quantity)이 자꾸 헷갈리고 로직상에서도 혼란스러우니 stock field도 제거하는 방향으로 가도 좋습니다. 
이 부분은 Cart 클래스의 구현이라 유빈님이 결정해주시면 될 것 같습니다.
